#!/bin/sh
set -e
#DEBHELPER## Manually added by packager
for user in `awk -F: '$3 >= 1000 && $3 < 60000 {print $1}' /etc/passwd`; do
	su - $user -c "rm -f ~/.config/autostart/autolocation.desktop"
done
rm -f "/etc/network/if-up.d/autolocation"
# End manually added section
