.TH LOCATION "1" "May 2015" "Distro Astro Location" "User Commands"
.SH NAME
location \- show the location and timezone
.SH SYNOPSIS
.B location
[\fIOPTION\fR]...
.SH DESCRIPTION
Display the location and timezone information.
.SH OPTIONS
.TP
\fB\-l\fR, \fB\-\-lat\fR
show latitude
.TP
\fB\-L\fR, \fB\-\-long\fR
show longitude
.TP
\fB\-e\fR, \fB\-\-elev\fR
show elevation
.TP
\fB\-S\fR, \fB\-\-street\fR
show street name
.TP
\fB\-A\fR, \fB\-\-area\fR
show area within city
.TP
\fB\-C\fR, \fB\-\-city\fR
show city name
.TP
\fB\-r\fR, \fB\-\-region\fR
show region within country
.TP
\fB\-c\fR, \fB\-\-country\fR
show country name
.TP
\fB\-2\fR, \fB\-\-cc\fR
show two\-letter country code
.TP
\fB\-z\fR, \fB\-\-tzid\fR
show timezone identifier
.TP
\fB\-t\fR, \fB\-\-tzname\fR
show timezone name
.TP
\fB\-b\fR, \fB\-\-tzabbr\fR
show timezone abbreviation
.TP
\fB\-o\fR, \fB\-\-utcoffset\fR
show timezone UTC offset
.TP
\fB\-O\fR, \fB\-\-dstoffset\fR
show timezone DST offset
.TP
\fB\-I\fR, \fB\-\-icao\fR
show ICAO code of nearest airport
.TP
\fB\-a\fR, \fB\-\-all\fR
show all of the above information
.TP
\fB\-s\fR, \fB\-\-short\fR
show requested information in short format
.TP
\fB\-h\fR, \fB\-\-help\fR
display this help and exit
.TP
\fB\-V\fR, \fB\-\-version\fR
output version information and exit
.SH AUTHOR
Written by Bamm Gabriana.
.SH "REPORTING BUGS"
Report location bugs to Bamm Gabriana <bamm@distroastro.org>
.br
Distro Astro home page: <http://www.distroastro.org/>
.SH COPYRIGHT
Copyright \(co 2014\-2015 Bamm Gabriana.
License GPLv2+: GPL version 2 or later <http://gnu.org/licenses/gpl\-2.0.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
