#!/bin/sh

################################################################################
#                                                                              #
# Distro Astro Location                                                        #
# Version 4.0                                                                  #
#                                                                              #
# Copyright (C) 2014-2017 Bamm Gabriana.                                       #
#                                                                              #
# This program is free software; you can redistribute it and/or modify         #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation; either version 2 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# This program is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with this program. If not, see <http://www.gnu.org/licenses/>          #
#                                                                              #
# On Debian systems, the complete text of the GNU General Public License       #
# version 2 and 3 can be found in                                              #
# "/usr/share/common-licenses/GPL-2" and "/usr/share/common-licenses/GPL-3".   #
#                                                                              #
################################################################################

exec="$(basename $0)"
ver="4.0"

# Process command line arguments.
for i do
	if [ -z "$i" ]; then false
	# All options.
	elif [ "$i" = "-h" -o "$i" = "--help"     ]; then	help="$i"
	elif [ "$i" = "-V" -o "$i" = "--version"  ]; then	version="$i"
	# Remaining arguments.
	elif echo $i | grep " " >/dev/null; then
		args="$args \"$i\""
	else
		args="$args $i"
	fi
	_="$i"
done
args=$(echo $args | sed 's/^ //g')

main() {

	lcargs=$(echo $args | tr '[:upper:]' '[:lower:]')

	if [ "$(id -u)" != "0" ]; then

		# Turn on / off
		location="/etc/location"
		plugins="/etc/distroastro/location/apps"
		autolocation="$HOME/.config/autostart/autolocation.desktop"
		autolocation_0="/etc/skel/.config/autostart/autolocation.desktop"

		if [ "$lcargs" = "on" ]; then
			# Turn on for current user.
			if [ ! -e "$autolocation" ]; then
				cp "$autolocation_0" "$autolocation" &
				$0 "set" &
			else
				echo "Already on."
			fi
			exit 0
		fi
		if [ "$lcargs" = "off" ]; then
			# Turn off for current user.
			if [ -e "$autolocation" ]; then
				rm -f "$autolocation" &
			else
				echo "Already off."
			fi
			exit 0
		fi
		if [ "$lcargs" = "status" ]; then
			# Display status for current user.
			if [ -e "$autolocation" ]; then
				echo "Autolocation is on."
			else
				echo "Autolocation is off."
			fi
			exit 0
		fi
		if [ "$lcargs" = "set" ]; then
			# Set location for current user.
			if [ -e "$location" ]; then
				for app in `ls "$plugins"`; do
					configure-location -q $app 2>/dev/null &
				done
			else
				echo "Unable to update location."
			fi
			exit 0
		fi
		echo "Try \`$exec --help' for more information."

	else

		autolocation="/etc/network/if-up.d/autolocation"
		autolocation_0="/usr/bin/autolocation"

		if [ "$lcargs" = "autostart" ]; then
			# Automatically start if network is up.
			if [ ! -e $autolocation ]; then
				ln -s $autolocation_0 $autolocation
			else
				echo "Already autostarts."
			fi
			exit 0
		fi

		if [ "$lcargs" = "dontautostart" ]; then
			# Don't automatically start if network is up.
			if [ -e $autolocation ]; then
				rm -f $autolocation
			else
				echo "Already does not autostart."
			fi
			exit 0
		fi

		# Update system location.
		update-location -q --force 2>/dev/null; exitcode=$?
		# Set location for all logged in users.
		if [ -e "/etc/location" ]; then
			for user in `users`; do
				home=$(su - $user -c "echo ~")
				if [ -e "$home/.config/autostart/autolocation.desktop" ]; then
					su - $user -c "$0 set" &
				fi
			done
			configure-location all -q &
		else
			echo "Unable to update location."
		fi
		exit $exitcode
	fi
}

showhelp() {
	echo "Usage: $exec [ on | off | set | status ]"
	echo ""
	echo "Turn on or turn off automatic configuration of location settings of supported"
	echo "apps for the current user."
	echo ""
	echo "  -h, --help		display this help and exit"
	echo "  -V, --version		output version information and exit"
	echo ""
	echo "Report $exec bugs to Bamm Gabriana <bamm@distroastro.org>"
	echo "Distro Astro home page: <http://www.distroastro.org/>"
}

showversion() {
	echo "$exec $ver"
	echo "Copyright (C) 2014-2015 Bamm Gabriana."
	echo "License GPLv2+: GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>."
	echo "This is free software: you are free to change and redistribute it."
	echo "There is NO WARRANTY, to the extent permitted by law."
	echo ""
	echo "Written by Bamm Gabriana."
}

[ -n "$help" ] && showhelp && exit
[ -n "$version" ] && showversion && exit
main

