#!/usr/bin/perl -w

################################################################################
#                                                                              #
# Distro Astro Location                                                        #
# Version 4.0                                                                  #
#                                                                              #
# Copyright (C) 2014-2017 Bamm Gabriana.                                       #
#                                                                              #
# This program is free software; you can redistribute it and/or modify         #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation; either version 2 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# This program is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with this program. If not, see <http://www.gnu.org/licenses/>          #
#                                                                              #
# On Debian systems, the complete text of the GNU General Public License       #
# version 2 and 3 can be found in                                              #
# "/usr/share/common-licenses/GPL-2" and "/usr/share/common-licenses/GPL-3".   #
#                                                                              #
################################################################################

use strict;
use warnings;

my ($exec, $longname) = ("gpredict", "GPredict");

use Getopt::Long;
Getopt::Long::Configure('bundling');

my ($quiet, $verbose, $debug, $help, $version);

GetOptions(
	'q|quiet'	=> \$quiet,
	'v|verbose'	=> \$verbose,
	'd|debug'	=> \$debug,
	'h|help'	=> \$help,
	'V|version'	=> \$version,
) or print STDERR "Try `$exec --help' for more information.\n" and exit 2;

$quiet = 0 if $verbose || $debug;
$quiet = $quiet ? "-q" : "";
$verbose = $verbose ? "-v" : "";
$debug = $debug ? "-d" : "";

exit if (! @ARGV);
exit if (! `which $exec`);

my ($LATITUDE, $LONGITUDE, $ELEVATION, $CITY, $REGION, $COUNTRY, $COUNTRYCODE, $TIMEZONE, $TZABBR, $TZOFFSET, $TZDSTOFFSET, $ICAO) = @ARGV;

sub main {
	exit if !$<;
	&setlocation;
}

sub setlocation {

	print "Configuring $longname...\n" if $verbose;

	# Convert to app-specific data format.

	my $LocationDesc = "Default Ground Station";
	my $LocationName = $REGION ? "$CITY, $REGION, $COUNTRY" : "$CITY, $COUNTRY";
	$ELEVATION = sprintf "%d", $ELEVATION;

	# Write down configuration data.

	my $conffile = "$ENV{HOME}/.config/Gpredict/Home.qth";
	my $defconffile = "/usr/share/gpredict/data/sample.qth";
	if (! -e $conffile) {
		if (! -e $defconffile) {
			print STDERR "Skipped $longname.\n";
			exit 1;
		}
		else {
			system "mkdir -p $ENV{HOME}/.config/Gpredict";
			system "cp $defconffile $conffile";
			system "cp /etc/skel/.config/Gpredict/gpredict.cfg $ENV{HOME}/.config/Gpredict";
		}
	}

	open FILE, "$conffile";
	my @lines = <FILE>;
	close FILE;

	for my $line (@lines) {
		$line =~ s/^DESCRIPTION=.*/DESCRIPTION=$LocationDesc/;
		$line =~ s/^LOCATION=.*/LOCATION=$LocationName/;
		$line =~ s/^LAT=.*/LAT=$LATITUDE/;
		$line =~ s/^LON=.*/LON=$LONGITUDE/;
		$line =~ s/^ALT=.*/ALT=$ELEVATION/;
		$line =~ s/^WX=.*/WX=$ICAO/;
	}

	my $filesize = -s "$conffile";

	open FILE, ">$conffile";
	if ($filesize < 48) {
		print FILE "[QTH]\n";
		print FILE "DESCRIPTION=$LocationDesc\n";
		print FILE "LOCATION=$LocationName\n";
		print FILE "LAT=$LATITUDE\n";
		print FILE "LON=$LONGITUDE\n";
		print FILE "ALT=$ELEVATION\n";
		print FILE "WX=$ICAO\n";
	}
	else {
		print FILE @lines;
	}
	close FILE;
}

main;
