#!/usr/bin/perl -w

################################################################################
#                                                                              #
# Distro Astro Location                                                        #
# Version 4.0                                                                  #
#                                                                              #
# Copyright (C) 2014-2017 Bamm Gabriana.                                       #
#                                                                              #
# This program is free software; you can redistribute it and/or modify         #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation; either version 2 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# This program is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with this program. If not, see <http://www.gnu.org/licenses/>          #
#                                                                              #
# On Debian systems, the complete text of the GNU General Public License       #
# version 2 and 3 can be found in                                              #
# "/usr/share/common-licenses/GPL-2" and "/usr/share/common-licenses/GPL-3".   #
#                                                                              #
################################################################################

use strict;
use warnings;

my ($exec, $longname) = ("stellarium", "Stellarium");

use Getopt::Long;
Getopt::Long::Configure('bundling');

my ($quiet, $verbose, $debug, $help, $version);

GetOptions(
	'q|quiet'	=> \$quiet,
	'v|verbose'	=> \$verbose,
	'd|debug'	=> \$debug,
	'h|help'	=> \$help,
	'V|version'	=> \$version,
) or print STDERR "Try `$exec --help' for more information.\n" and exit 2;

$quiet = 0 if $verbose || $debug;
$quiet = $quiet ? "-q" : "";
$verbose = $verbose ? "-v" : "";
$debug = $debug ? "-d" : "";

exit if (! @ARGV);
exit if (! `which $exec`);

my ($LATITUDE, $LONGITUDE, $ELEVATION, $CITY, $REGION, $COUNTRY, $COUNTRYCODE, $TIMEZONE, $TZABBR, $TZOFFSET, $TZDSTOFFSET, $ICAO) = @ARGV;

sub main {
	exit if !$<;
	&setlocation;
}

sub setlocation {

	print "Configuring $longname...\n" if $verbose;

	# Convert to app-specific data format.

	my $NS = ($LATITUDE >= 0) ? "N" : "S";
	my $EW = ($LONGITUDE >= 0) ? "E" : "W";

	$LATITUDE = sprintf("%6.6f", $LATITUDE);
	$LONGITUDE = sprintf("%6.6f", $LONGITUDE);

	my $LocationData = "$CITY, $REGION\t\t$COUNTRY\tX\t\t$LATITUDE$NS\t$LONGITUDE$EW\t$ELEVATION\t2\t\tEarth\t\n";

	my ($D, $M, $S, $H);

	($D, $M, $S, $H) = Dec2DMS("$LATITUDE");
	my $LatDMS = "${H}${D}d${M}'${S}\"";

	($D, $M, $S, $H) = Dec2DMS("$LONGITUDE");
	my $LongDMS = "${H}${D}d${M}'${S}\"";

	my $LocationName = $REGION ? "$CITY, $REGION, $COUNTRY" : "$CITY, $COUNTRY";

	# Write down configuration data.

	my $conffile = "$ENV{HOME}/.stellarium/config.ini";
	my $defconffile = "/usr/share/stellarium/data/default_config.ini";
	if (! -e $conffile) {
		if (! -e $defconffile) {
			print STDERR "Skipped $longname.\n";
			exit 1;
		}
		else {
			system "mkdir -p $ENV{HOME}/.stellarium";
			system "cp $defconffile $conffile";
		}
	}

	my @places;
	my $placesfile = "$ENV{HOME}/.stellarium/data/user_locations.txt";
	if (-e $placesfile) {
		open FILE, "$placesfile";
		@places = <FILE>;
		close FILE;
	}

	if (!grep(/$LocationData/, @places)) {

		my $found = 0;
		for my $place (@places) {
			if ($place =~ m/^$CITY, $REGION\t\t$COUNTRY\t/) {
				$place = $LocationData;
				$found++;
			}
		}
		if (!$found) {
			push @places, "$LocationData";
		}

		`mkdir -p $ENV{HOME}/.stellarium/data/`;
		open FILE, ">$placesfile";
		print FILE @places;
		close FILE;
	}

	open FILE, "$conffile";
	my @lines = <FILE>;
	close FILE;

	for my $line (@lines) {
		$line =~ s/^(|\s+)location(\s+)=.*/${1}location${2}= $LocationName/;
		$line =~ s/^(|\s+)name(\s+)=.*/${1}name${2}= $LocationName/;
		$line =~ s/^(|\s+)latitude(\s+)=.*/${1}latitude${2}= $LatDMS/;
		$line =~ s/^(|\s+)longitude(\s+)=.*/${1}longitude${2}= $LongDMS/;
		$line =~ s/^(|\s+)altitude(\s+)=.*/${1}altitude${2}= $ELEVATION/;
		$line =~ s/^(|\s+)time_zone(\s+)=.*/${1}time_zone${2}= $TIMEZONE/;
	}

	open FILE, ">$conffile";
	print FILE @lines;
	close FILE;
}

sub Dec2DMS {
	my $dec = $_[0];
	my $sgn = ($dec >= 0) ? "+" : "-";
	$dec = abs $dec;
	my $deg = sprintf("%1d", $dec);
	$dec = $dec - $deg;
	$dec = $dec * 60;
	my $min = sprintf("%02d", $dec);
	$dec = $dec - $min;
	$dec = $dec * 60;
	my $sec = sprintf("%05.2f", $dec);
	return ($deg, $min, $sec, $sgn);
}

main;

