#!/usr/bin/perl -w

################################################################################
#                                                                              #
# Distro Astro Location                                                        #
# Version 4.0                                                                  #
#                                                                              #
# Copyright (C) 2014-2017 Bamm Gabriana.                                       #
#                                                                              #
# This program is free software; you can redistribute it and/or modify         #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation; either version 2 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# This program is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with this program. If not, see <http://www.gnu.org/licenses/>          #
#                                                                              #
# On Debian systems, the complete text of the GNU General Public License       #
# version 2 and 3 can be found in                                              #
# "/usr/share/common-licenses/GPL-2" and "/usr/share/common-licenses/GPL-3".   #
#                                                                              #
################################################################################

use strict;
use warnings;

my ($exec, $longname) = ("xephem", "XEphem");

use Getopt::Long;
Getopt::Long::Configure('bundling');

my ($quiet, $verbose, $debug, $help, $version);

GetOptions(
	'q|quiet'	=> \$quiet,
	'v|verbose'	=> \$verbose,
	'd|debug'	=> \$debug,
	'h|help'	=> \$help,
	'V|version'	=> \$version,
) or print STDERR "Try `$exec --help' for more information.\n" and exit 2;

$quiet = 0 if $verbose || $debug;
$quiet = $quiet ? "-q" : "";
$verbose = $verbose ? "-v" : "";
$debug = $debug ? "-d" : "";

exit if (! @ARGV);
exit if (! `which $exec`);

my ($LATITUDE, $LONGITUDE, $ELEVATION, $CITY, $REGION, $COUNTRY, $COUNTRYCODE, $TIMEZONE, $TZABBR, $TZOFFSET, $TZDSTOFFSET, $ICAO) = @ARGV;

sub main {
	exit if !$<;
	&setlocation;
}

sub setlocation {

	print "Configuring $longname...\n" if $verbose;

	# Convert to app-specific data format.

	my ($D, $M, $S, $H);

	($D, $M, $S, $H) = Dec2DMS("$LATITUDE");
	$S = sprintf("%02d", $S);
	$H = ($H eq "-") ? "-" : "";
	my $LatDMS = "$H${D}:${M}:${S}";

	($D, $M, $S, $H) = Dec2DMS("$LONGITUDE");
	$S = sprintf("%02d", $S);
	$H = ($H eq "+") ? "-" : "";
	my $LongDMS = "$H${D}:${M}:${S}";

	($D, $M, $S, $H) = Dec2DMS($TZOFFSET / 3600);
	$S = sprintf("%02d", $S);
	$H = ($H eq "+") ? "-" : "";
	my $TZDMS = "$H${D}:${M}:${S}";

	my $ElevMeters = sprintf("%4.1f", $ELEVATION);

	my $LocationName = $REGION ? "$CITY, $REGION, $COUNTRY" : "$CITY, $COUNTRY";

	# Write down configuration data.

	my $conffile = "$ENV{HOME}/.xephem/XEphem";
	my $defconffile = "/etc/X11/app-defaults/XEphem";
	if (! -e $conffile) {
		if (! -e $defconffile) {
			print STDERR "Skipped $longname.\n";
			exit 1;
		}
		else {
			system "mkdir -p $ENV{HOME}/.xephem";
			system "cp $defconffile $conffile";
		}
	}

	open FILE, "$conffile";
	my @lines = <FILE>;
	close FILE;

	for my $line (@lines) {
		$line =~ s/XEphem\.Lat:        .*/XEphem\.Lat:                                  $LatDMS/;
		$line =~ s/XEphem\.Long:       .*/XEphem\.Long:                                 $LongDMS/;
		$line =~ s/XEphem\.Elevation:  .*/XEphem\.Elevation:                            $ElevMeters m/;
		$line =~ s/XEphem\.Sitename:   .*/XEphem\.Sitename:                             $LocationName/;
		$line =~ s/XEphem\.TZName:     .*/XEphem\.TZName:                               $TZABBR/;
		$line =~ s/XEphem\.TZone:      .*/XEphem\.TZone:                                $TZDMS/;
	}

	open FILE, ">$conffile";
	print FILE @lines;
	close FILE;
}

sub Dec2DMS {
	my $dec = $_[0];
	my $sgn = ($dec >= 0) ? "+" : "-";
	$dec = abs $dec;
	my $deg = sprintf("%1d", $dec);
	$dec = $dec - $deg;
	$dec = $dec * 60;
	my $min = sprintf("%02d", $dec);
	$dec = $dec - $min;
	$dec = $dec * 60;
	my $sec = sprintf("%05.2f", $dec);
	return ($deg, $min, $sec, $sgn);
}

main;

