#!/bin/sh
set -e
#DEBHELPER## Manually added by packager
if [ -x /usr/bin/apt-key ]; then
    apt-key add /usr/share/keyrings/distroastro-archive-keyring.gpg > /dev/null
fi
# End manually added section
