#!/usr/bin/perl -w

################################################################################
#                                                                              #
# Toggle Nightvision                                                           #
# Version 3.0                                                                  #
#                                                                              #
# Copyright (C) 2011-2014 Bamm Gabriana.                                       #
#                                                                              #
# This program is free software; you can redistribute it and/or modify         #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation; either version 2 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# This program is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with this program. If not, see <http://www.gnu.org/licenses/>          #
#                                                                              #
# On Debian systems, the complete text of the GNU General Public License       #
# version 2 and 3 can be found in                                              #
# "/usr/share/common-licenses/GPL-2" and "/usr/share/common-licenses/GPL-3".   #
#                                                                              #
################################################################################

use strict;
use warnings;

exit if (! `which nightshade`);
exit if (! @ARGV);

use Getopt::Long;
Getopt::Long::Configure('bundling');

my ($quiet, $verbose);

exit unless GetOptions(
	'q|quiet'   => \$quiet,
	'v|verbose' => \$verbose,
);

my $conffile = "$ENV{HOME}/.nightshade/config.ini";
my $defconffile = "/usr/share/nightshade/data/default_config.ini";
if (! -e $conffile) {
	if (! -e $defconffile) {
		print STDERR "Error: $conffile not found.\n";
		exit 1;
	}
	else {
		system "mkdir -p $ENV{HOME}/.nightshade";
		system "cp $defconffile $conffile";
	}
}

open FILE, "$conffile";
my @lines = <FILE>;
close FILE;

if ($ARGV[0] eq "Nightvision") {
	for my $line (@lines) {
		$line =~ s/flag_night(\s+)=.*/flag_night$1= true/;

	}
	print "Nightshade Nightvision ON.\n" if $verbose;
}

else {
	for my $line (@lines) {
		$line =~ s/flag_night(\s+)=.*/flag_night$1= false/;
	}
	print "Nightshade Nightvision OFF.\n" if $verbose;
}

open FILE, ">$conffile";
print FILE @lines;
close FILE;

