#!/bin/sh

################################################################################
#                                                                              #
# Distro Astro Planetarium                                                     #
# Version 4.0                                                                  #
#                                                                              #
# Copyright (C) 2014-2015 Bamm Gabriana.                                       #
#                                                                              #
# This program is free software; you can redistribute it and/or modify         #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation; either version 2 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# This program is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with this program. If not, see <http://www.gnu.org/licenses/>          #
#                                                                              #
# On Debian systems, the complete text of the GNU General Public License       #
# version 2 and 3 can be found in                                              #
# "/usr/share/common-licenses/GPL-2" and "/usr/share/common-licenses/GPL-3".   #
#                                                                              #
################################################################################

if [ `id -u` != 0 ] ; then
    echo "This script must be run with root privileges."
    exit 1
fi

useradd -m --skel="/usr/share/planetarium/skel" --shell="/bin/bash" -c "Planetarium" planetarium 2> /dev/null
echo planetarium:planetarium | chpasswd
usermod -a -G nopasswdlogin planetarium

