#!/bin/sh

################################################################################
#                                                                              #
# Distro Astro Planetarium                                                     #
# Version 4.0                                                                  #
#                                                                              #
# Copyright (C) 2014-2015 Bamm Gabriana.                                       #
#                                                                              #
# This program is free software; you can redistribute it and/or modify         #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation; either version 2 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# This program is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with this program. If not, see <http://www.gnu.org/licenses/>          #
#                                                                              #
# On Debian systems, the complete text of the GNU General Public License       #
# version 2 and 3 can be found in                                              #
# "/usr/share/common-licenses/GPL-2" and "/usr/share/common-licenses/GPL-3".   #
#                                                                              #
################################################################################

exec="$(basename $0)"
ver="4.0"

# Process command line arguments.
for i do
	if [ -z "$i" ]; then false
	# All options.
	elif [ "$i" = "-q" -o "$i" = "--quiet"    ]; then	quiet="$i"
	elif [ "$i" = "-d" -o "$i" = "--debug"    ]; then	debug="$i"
	elif [ "$i" = "-h" -o "$i" = "--help"     ]; then	help="$i"
	elif [ "$i" = "-V" -o "$i" = "--version"  ]; then	version="$i"
	# Remaining arguments.
	elif echo $i | grep " " >/dev/null; then
		args="$args \"$i\""
	else
		args="$args $i"
	fi
	_="$i"
done
args=$(echo $args | sed 's/^ //g')

main() {

	planetarium=$args

	if [ -z $planetarium ]; then

		if command -v nightshade >/dev/null; then
			planetarium=nightshade
		elif command -v stellarium >/dev/null; then
			planetarium=stellarium
		else
			echo "Please install Nightshade or Stellarium."
			exit 2
		fi
	fi

	if [ $planetarium = "nightshade" ] || [ $planetarium = "stellarium" ]; then

		if command -v $planetarium >/dev/null; then

			[ $planetarium = "nightshade" ] && Planetarium="Nightshade"
			[ $planetarium = "stellarium" ] && Planetarium="Stellarium"

			echo "Starting planetarium show..."

			echo "Configuring $Planetarium settings..."

			if command -v configure-resolution >/dev/null; then
				configure-resolution -iq $planetarium
			fi

			if command -v configure-location >/dev/null; then
				configure-location -iq $planetarium
			fi

			echo "Starting $Planetarium..."
			[ -z "$debug" ] && $planetarium

		else
			echo "\`$planetarium' is not installed. Try sudo apt-get install $planetarium."
			exit 2
		fi

	else
		echo "Possible values for planetarium are \`nightshade' and \`stellarium'."
		exit 1
	fi
}

showhelp() {
	echo "Usage: $exec [OPTION]... [nightshade|stellarium]"
	echo ""
	echo "Configure the location, timezone, and screen resolution before starting the"
	echo "planetarium program."
	echo ""
	echo "  -h  --help     display this help and exit"
	echo "  -V  --version  output version information and exit"
	echo ""
	echo "Report $exec bugs to Bamm Gabriana <bamm@distroastro.org>"
	echo "Distro Astro home page: <http://www.distroastro.org/>"
}

showversion() {
	echo "$exec $ver"
	echo "Copyright (C) 2014-2015 Bamm Gabriana."
	echo "License GPLv2+: GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>."
	echo "This is free software: you are free to change and redistribute it."
	echo "There is NO WARRANTY, to the extent permitted by law."
	echo ""
	echo "Written by Bamm Gabriana."
}

[ -n "$help" ] && showhelp && exit
[ -n "$version" ] && showversion && exit
main

