.TH PLANETARIUM "1" "May 2015" "Start Planetarium" "User Commands"
.SH NAME
planetarium \- start the planetarium show.
.SH SYNOPSIS
.B planetarium
[\fIOPTION\fR]... [\fInightshade|stellarium\fR]
.SH DESCRIPTION
Configure the location, timezone, and screen resolution before starting the
planetarium program.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
display this help and exit
.TP
\fB\-V\fR, \fB\-\-version\fR
output version information and exit
.SH AUTHOR
Written by Bamm Gabriana.
.SH "REPORTING BUGS"
Report planetarium bugs to Bamm Gabriana <bamm@distroastro.org>
.br
Distro Astro home page: <http://www.distroastro.org/>
.SH COPYRIGHT
Copyright \(co 2014-2015 Bamm Gabriana.
License GPLv2+: GPL version 2 or later <http://gnu.org/licenses/gpl\-2.0.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
